config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get 'pages/index'

  get "/auth/:provider/callback" =>  "sessions#create"

  resources :users do
    member do
      get :flop_availability
      get :make_student
      get :make_tutor
    end
  end
  get 'user/:id/decision', to: "users#decision", as: "decision"

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :uid, :provider, presence: true

  def self.build_from_github(auth_hash)
    user       = User.new
    user.uid   = auth_hash[:uid]
    user.provider = 'github'
    user.name  = auth_hash['info']['name']
    user.email = auth_hash['info']['email']

    return user
  end

  def working
    return at_ada || remote
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth_hash = request.env['omniauth.auth']
    redirect to login_failure_path unless auth_hash['uid']

    @user = User.find_by(uid: auth_hash[:uid], provider: 'github')
    if @user.nil?
      # User doesn't match anything in the DB.
      # Attempt to create a new user.
      @user = User.build_from_github(auth_hash)
      render :creation_failure unless @user.save
    end

    # Save the user ID in the session
    session[:user_id] = @user.id


    if @user.student == nil
      redirect_to decision_path(@user)
    elsif @user.student
      redirect_to users_path
    else
      redirect_to user_path(@user)
    end
  end

  def index
    @user = User.find(session[:user_id]) # < recalls the value set in a previous request
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :decision, :make_student, :make_tutor]

  # GET /users
  # GET /users.json

  def index
    @users = User.where(at_ada: true).or.where(remote: true).order("available DESC", "at_ada DESC").all

    @encouragement = [
      "Drink some water.",
      "Call your person.",
      "Take a stretch break.",
      "Try talking it out with you rubber duck.",
      "Ask a friend to listen to you talk through your problem.",
      "Go for a short walk.",
      "Put on your favorite music and take a little break.",
      "Close your laptop for a few minutes.",
      "Did you restart your server?"
    ].sample
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def decision
  end

  def make_student
      @user.student = true
      @user.save

      redirect_to users_path
  end

  def make_tutor
      @user.student = false
      @user.save

      redirect_to user_path(@user)
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :twitter, :screenhero, :company, :languages, :pronouns, :at_ada, :remote, :available, :physical_description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TAFinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<div class="headspace">
</div>

<div class="container homepage">
  <h1>Who's Tutoring at Ada Right Now?</h1>
  <%= button_to "Sign in with Github", "auth/github" %>
  <div>
    <%= link_to "Sign up", 'auth/github' %>
  </div>
</div>

<footer>
</footer>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :screenhero %><br>
    <%= f.text_field :screenhero %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :languages %><br>
    <%= f.text_area :languages %>
  </div>
  <div class="field">
    <%= f.label :pronouns %><br>
    <%= f.text_field :pronouns %>
  </div>
  <div class="field">
    <%= f.label :at_ada %><br>
    <%= f.check_box :at_ada %>
  </div>
  <div class="field">
    <%= f.label :remote %><br>
    <%= f.check_box :remote %>
  </div>
  <div class="field">
    <%= f.label :available %><br>
    <%= f.check_box :available %>
  </div>
  <div class="field">
    <%= f.label :physical_description %><br>
    <%= f.text_area :physical_description %>
  </div>
  <div class="field">
    <%= f.label :pronouns %><br>
    <%= f.check_box :pronouns %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/decision.html.erb
<div class="headspace">
</div>

<div class="container decision">
  <h1>I am a:</h1>
  <div>
    <%= button_to "Student", make_student_user_path(@user), method: :get %>
    <%= button_to "Tutor", make_tutor_user_path(@user), method: :get  %>
  </div>

</div>

<footer>
</footer>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<% if @users.length == 0 %>
  <div class="headspace"></div>
  <div class="container">
    <h1>There are no tutors working right now. </h1>
    <h1><%= @encouragement %></h1>
  </div>
<% else %>
  <div class="container">
    <h1>Tutors Working Right Now</h1>
    <section class="all-tutors row">
      <% @users.each do |user| %>
        <% if user.student == false && ( user.at_ada || user.remote ) %>
          <section class="one-tutor four columns available-<%= user.available %>">
            <img src="assets/beyonce.jpg" />
            <% if user.available %>
              <div>
                AVAILABLE
                <% if user.at_ada %>
                  AT ADA
                <% else %>
                  REMOTELY
                <% end %>
              </div>
            <% end %>
            <h3><%= user.name %></h3>
            <p class="pronoun"><%= user.pronouns %></p>
            <% if user.at_ada %>
              <p><b>Physical Identifier:</b> <%= user.physical_description %></p>
            <% end %>
            <% if user.remote %>
              <p><b>How to Contact:</b> <%= user.physical_description %></p>
            <% end %>
          </section>
        <% end %>
      <% end %>
    </section>
  </div>
<% end %>
<footer>

</footer>

<script>
  setTimeout("location.reload(true);", 20000);
</script>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @user.name %>
</p>

  <strong>Pronouns:</strong>
  <%= @user.pronouns %>
</p>

<p>
  <strong>At ada:</strong>
  <%= @user.at_ada %>
</p>

<p>
  <strong>Remote:</strong>
  <%= @user.remote %>
</p>

<p>
  <strong>Available:</strong>
  <%= @user.available %>
</p>

<p>
  <strong>Physical description:</strong>
  <%= @user.physical_description %>
</p>

<p>
  <strong>Pronouns:</strong>
  <%= @user.pronouns %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |